name: code-pipeline-build-test

on:
  push:
    paths:
      - 'cobol/**'
      
jobs:
  run-code-pipeline-build:
    runs-on: ubuntu-latest
    env:
      Win_Topaz_Location: 'C:\WorkbenchCLI ' #local desktop    
    name: A job to sync git source into Code Pipeline, then build it on the mainframe
    steps:
      - name: Sync step
        uses: bmc-compuware/ispw-sync@v1
        id: sync
        with:
          host: 'BMC.POPUP-MAINFRAME.COM'
          port: 16196
          uid: 'IBMUSER'
          pass: ${{ secrets.HOST_172_PWD }}
          runtimeConfiguration: 'ISPT'
          stream: 'PLAY'
          application: 'TEST'
          checkoutLevel: 'DEV1'
          gitUid: 'gomathibose01'
          gitPass: ${{ secrets.GIT_MY_PWD }}
          showEnv: true
          encryptionProtocol: None
          codePage: 1047

      - name: Get automatic build parameters
        run: echo "automaticBuildJson=${{ steps.sync.outputs.automaticBuildJson }}"

      - name: Build
        uses: bmc-compuware/ispw-build@v1
        id: build
        with:
          ces_url: 'http://10.10.1.174:48226/'
          ces_token: ${{ secrets.CES_172_IBMUSER_TOKEN }}
          srid: 'ISPT'
          runtime_configuration: 'ISPT'
          build_automatically: ${{ steps.sync.outputs.automaticBuildJson }}

      - name: wait 15 seconds for generate to complete
        run: Start-Sleep -s 15
        shell: powershell       
      
      - name: Get the number of generate failures
        run: echo "The number of generate failures is ${{ steps.build.outputs.generate_failed_count }}"
