
name: CESAPI_BACKOUTJCLs

on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: [self-hosted, Windows]
    env:
      PATH: 'C:\Program Files\Git\bin'
      CESAPI_SERVER: ${{ secrets.CESAPI_SERVER }}
      CES_204_IBMUSER_AUTHTOKEN: ${{ secrets.CES_204_IBMUSER_AUTHTOKEN }}
      PDS_NAME: 'IBMUSER.NEXTGEN.BACKOUT.JCL'
    steps:
        - name: Run Bash script - Backout JCL submission
          run: bash C:\dev\2024\NextGenKansas\cesAPI_backoutjcl_v1.sh        
