name: CESAPI_BUILDJCL1

on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: [self-hosted, Windows]
    
    env:
      PATH: 'C:\Program Files\Git\bin'
      CESAPI_SERVER: ${{ secrets.CESAPI_SERVER }}
      CES_204_IBMUSER_AUTHTOKEN: ${{ secrets.CES_204_IBMUSER_AUTHTOKEN }}
      PDS_NAME: 'IBMUSER.NEXTGEN.JCL'
    steps:
        - name: JCL submission #1 thru #10 / CES API calls via Bash script
          run: bash C:\dev\2024\NextGenKansas\cesAPI_buildjcl1_v1.sh
        - name: JCL submission $99NEWCP / CES API calls via Bash script
          run: bash C:\dev\2024\NextGenKansas\cesAPI_buildjcl2_v1.sh
