name: CESAPI_BUILDJCL2

on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: [self-hosted, Windows]
    
    env:
      PATH: 'C:\Program Files\Git\bin'
    steps:
      - name: Run Bash script
        # shell: bash
        env:
          CESAPI_SERVER: ${{ secrets.CESAPI_SERVER }}
          CES_204_IBMUSER_AUTHTOKEN: ${{ secrets.CES_204_IBMUSER_AUTHTOKEN }}
          PDS_NAME: ${{ vars.PDS_NAME }}
        run: 
          bash C:\dev\2024\NextGenKansas\cesAPI_buildjcl2_v1.sh
        
