name: CESAPI_BUILDJCL

on:
  workflow_dispatch:

jobs:
  BuildApplicationcomponents:
    runs-on: [self-hosted, Windows]
    
    env:
      PATH: 'C:\Program Files\Git\bin'
      CESAPI_SERVER: ${{ secrets.CESAPI_SERVER }}
      CES_204_IBMUSER_AUTHTOKEN: ${{ secrets.CES_204_IBMUSER_AUTHTOKEN }}
      PDS_NAME: 'IBMUSER.NEXTGEN.JCL'
    steps:
        - name: JCL submission $1 thru $10 / CES API calls via Bash script
          run: bash C:\dev\2024\NextGenKansas\cesAPIscript\cesAPI_buildjcl1_v1.0.sh
        - name: JCL submission $99NEWCP / CES API calls via Bash script   
          run: bash C:\dev\2024\NextGenKansas\cesAPIscript\cesAPI_buildjcl2_v1.0.sh
