
name: CESAPI_BACKOUTJCL

on:
  workflow_dispatch:

jobs:
  BackoutApplication:
    runs-on: [self-hosted, Windows]
    env:
      PATH: 'C:\Program Files\Git\bin'
      CESAPI_SERVER: ${{ secrets.CESAPI_SERVER }}
      CES_204_IBMUSER_AUTHTOKEN: ${{ secrets.CES_204_IBMUSER_AUTHTOKEN }}
      PDS_NAME: 'IBMUSER.NEXTGEN.BACKOUT.JCL'
    steps:
        - name: Run Bash script - Backout JCL submission
          run: bash C:\dev\2024\NextGenKansas\cesAPIscript\cesAPI_backoutjcl_v1.0.sh -e {0}       
