name: color

on:
  workflow_dispatch:

jobs:
  job1-bash-script:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Set color
        env:
          shell: 'C:\Program Files\Git\bin\bash'
        id: color-selector
        run:  echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
            SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"
