name: color

on:
  workflow_dispatch:

jobs:
  Buildjclsubmision:
    runs-on: [self-hosted, Windows]
    
    env:
      PATH: 'C:\Program Files\Git\bin'
      CESAPI_SERVER: ${{ secrets.CESAPI_SERVER }}
      CES_204_IBMUSER_AUTHTOKEN: ${{ secrets.CES_204_IBMUSER_AUTHTOKEN }}
      PDS_NAME: 'IBMUSER.NEXTGEN.JCL'
    steps:
        - name: JCL submission #1 thru #10 / CES API calls via Bash script
          id: job1
          run: bash C:\dev\2024\NextGenKansas\cesAPI_buildjcl1_v1_condcheck1.sh
            #echo ::set-output name=exit_code::$?
        - name: JCL submission $99NEWCP / CES API calls via Bash script
          #if: steps.job1.outputs.exit_code == 0
          run: bash C:\dev\2024\NextGenKansas\cesAPI_buildjcl2_v1_condcheck.sh
