name: Bash Script
on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash script
        run: bash C:\Users\Dell\test_maskingapi_sh\maskingAPI_V1.0_TEST.sh
