name: Bash Script
on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: cloudflare/wrangler-action@v3

      - name: Run Bash script
        run: bash maskingAPI_V1.0_TEST.sh
