name: APITEST

on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: [self-hosted, Windows]

    env:
      PATH: 'C:\Program Files\Git\bin'
      MASKING_ENGINE: http://10.10.1.13/masking/api/v5.1.27
      APPLICATION_NAME: TESTGB1
      ENVIRONMENT_NAME: TESTGB1
      CONNECTION_NAME: CONNTEST1
      DATABASE_TYPE: DB2_MAINFRAME
      HOST_IP: 10.10.1.180
      PORT: 5040
      DBSCHEMA: EMPDBV02
      DBNAME: DALLASC
      RS_NAME: RS1
      INPUT_TABLE_NAME1: T_EMP_PERSONAL
      COLNAME: FIRSTNAME
      JOB_NAME: DEMOAMSK

    steps:
      - name: Set up Git for Windows
        shell: cmd
        run: |
          "C:\Program Files\Git\bin\bash.exe" --version

      - name: Run Bash script
        shell: bash
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        run: |
          bash C:\dev\2024\NextGenKansas\maskingAPI_V1.0tstgb.sh
